### ISSUE TITLE
Stream deck YT not working

### ISSUE THREAD

**Issue by GARFIELDISDOC** [claudiobernasconi/streamdeck-youtube#1]
Hey man, I added the YT stats and I did everything you told me too and its still not showing my YT stats. I even pressed the stream deck...

**Comment by claudiobernasconi** [comment]
Thank you for leaving this information. Can you specify what you did and can you send me the log?
If you don't know where to find the log file: https://www.reddit.com/r/StreamDeckSDK/comments/ap9qiu/is_there_any_logging_available_from_the_streamdeck/

**Comment by PirateSoftware** [comment]
Having the same issue.
Looks like the plugin is crashing as per the logs?
API key and Channel ID are correct.

06:26:18.382                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_bca3506446a761570b1e732702af118d>::operator ()(): The plugin 'YouTube Channel Statistics' crashed with code 1:-2147450740

**Comment by claudiobernasconi** [comment]
Thank you for reporting this issue. I'll migrate all reportings and will follow up on issue #2.
