### ISSUE TITLE
Streamdeck App not working

### ISSUE THREAD

**Issue by zmoli53** [claudiobernasconi/streamdeck-youtube#10]
I recently downloaded the install file for the streamdeck software, installed it, and then got the API and channel ID for my youtube channel, but nothing is showing on the elgato screen. I did this once before but I just recently reinstalled windows. I do not remember if I have to go into the command prompt and copy and paste anything. I have searched but have only found results that explain about the API and channel ID. Any suggestions?

**Comment by zmoli53** [comment]
figured it out!

**Comment by claudiobernasconi** [comment]
In case anyone finds this issue later on please check out my video where I explain step-by-step how to set up the plugin: https://www.youtube.com/watch?v=gqWgcuV5FK0
