### ISSUE TITLE
Add Sub Count to OBS

### ISSUE THREAD

**Issue by fabianBre** [claudiobernasconi/streamdeck-youtube#14]
Hey there, 

is it somehow possible to add the Sub Count also to OBS? (Or maybe to a self updating Textfile to add it to OBS)

**Comment by claudiobernasconi** [comment]
Hi @fabianBre.

That's definitely doable using the YouTube API. However, it's not the goal of this Stream Deck plugin. This repository contains the source code of the Stream Deck plugin. If you are a developer, feel free to implement a tool to use with OBS.

However, a quick search on YouTube showed me several videos that offer solutions for your use case. So maybe there is something that you can use without building it yourself.

**Comment by fabianBre** [comment]
You are right, there are some solutions, but mostly they need a Browser to be open or you are restricted regarding the looks of the implementation.

I dont need this function myself, but I am starting to learn Python, so maybe that would make a nice first project :D

**Comment by claudiobernasconi** [comment]
I wish you all the best with your project.
