### ISSUE TITLE
Plugin detected as malware by Malwarebytes

### ISSUE THREAD

**Issue by MarshM4ll0w** [claudiobernasconi/streamdeck-youtube#16]
As of today this Streamdeck plugin is being identified by Malwarebytes as a "Backdoor.Quasar"

Screenshot for reference: [https://ibb.co/1rxjW5m](https://ibb.co/1rxjW5m)

_Windows 10
Intel i9-10900k_

***Update***
This is clearly a False Positive.  Same issues referenced in the Malware Bytes Forum: [https://forums.malwarebytes.com/topic/280878-backdoorquasar-detected-on-streamdeck-plugin-for-cubase-possible-fp/#comment-1488401](url)

I am just making this post to be informational in case anyone else is seeing these alerts.

**Comment by claudiobernasconi** [comment]
@MarshM4ll0w Hi, thanks for reporting the issue. I highly appreciate your caution. I updated the application to use the latest libraries and tested it using **VirusTotal**: https://www.virustotal.com/gui/file/abb6fcef50e70f4960820958ecbb3d3b53732c07b94f1ba9d817101a10b22039?nocache=1

As you can see, almost all tools report **undetected**. 
I want to mention that Malwarebytes reports **undetected** too.

There is a false positive in MaxSecure. 

Feel free to run the test yourself with the version v1.2, which should be available in the Elgato StreamDeck Store soon.

I need to mention that the Elgato StreamDeck Plugin system is designed to execute other executables (for example, my plugin). It's their design choice, and if you have any concerns, you might want to stop using StreamDeck completely.

Alternatively, feel free to clone the repository and build the plugin yourself. It's open-source.
