### ISSUE TITLE
Plugin Crashes 

### ISSUE THREAD

**Issue by MyTekReview** [claudiobernasconi/streamdeck-youtube#3]
Here is part of the log ... every instance is the same error 

00:19:54.007                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_bca3506446a761570b1e732702af118d>::()::<lambda_bb91b78014718e2de5e781482a024c2e>::operator ()(): Restarting plugin 'YouTube Channel Statistics' after one minute
00:19:54.037                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_bca3506446a761570b1e732702af118d>::operator ()(): The plugin 'YouTube Channel Statistics' crashed with code 1:-2147450740
00:19:54.037                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_bca3506446a761570b1e732702af118d>::operator ()(): Restarting plugin 'YouTube Channel Statistics'
00:19:54.066                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_bca3506446a761570b1e732702af118d>::operator ()(): The plugin 'YouTube Channel Statistics' crashed with code 1:-2147450740

**Comment by claudiobernasconi** [comment]
Thank you for reporting this issue. I'll migrate all reportings and will follow up on issue #2.
