### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by PStrom** [claudiobernasconi/streamdeck-youtube#4]
The API Key and Channel ID are set, but there are no numbers visible for either subscribers or videos.

When I press the buttons there is a green triangle with an exclamation mark showing.

Any way to get some logs or something to help find the error?

**Comment by MyTekReview** [comment]
> The API Key and Channel ID are set, but there are no numbers visible for either subscribers or videos.
> 
> When I press the buttons there is a green triangle with an exclamation mark showing.
> 
> Any way to get some logs or something to help find the error?

It hasn't work for months, He reply to me and everyone else that have reported the issue that he will work on it ... We are just in the waiting game for now.

**Comment by claudiobernasconi** [comment]
Hi and welcome @PStrom.

As this is open-source and free of charge, I cannot treat this as my top priority. Nonetheless, I will work on it tomorrow and provide a new version with more insightful log messages. I close this issue to group the conversation in #2.
