### ISSUE TITLE
Is this a work in progress? No longer working

### ISSUE THREAD

**Issue by adrian97c** [claudiobernasconi/streamdeck-youtube#5]
Brand new Stream Deck, followed the setup guide.... all I get is yellow Triangle, tried resetting, reinstalling. It fails.

**Comment by claudiobernasconi** [comment]
Hi @adrian97c.

Thanks for reporting this issue. It seems to be an issue that many people have. You can read more details in #2, where I will continue to communicate about it. I'll work on it tomorrow.
