### ISSUE TITLE
API Key not working

### ISSUE THREAD

**Issue by RodneyMcKay715** [claudiobernasconi/streamdeck-youtube#7]
I created a Project at Google API and used the Youtube Data V3 API and also got my API and Channel Key. When i plug these values in the Buttons Menu (Subscriber Count) only the yellow warning appears. A Log file is included.

[StreamDeck0.log](https://github.com/claudiobernasconi/streamdeck-youtube/files/4699240/StreamDeck0.log)

**Comment by claudiobernasconi** [comment]
Thank you for reporting this issue. There was a known issue documented in more detail in #2. Please download the latest version 1.1, which was made available a few hours ago on the Stream Deck store.

Please report back if it fixes your problem.

**Comment by RodneyMcKay715** [comment]
It works properly now, i closed the issue because i just redownloaded and reinstalled the plugin and it worked fine. I thought i had done something wrong on my part.

Working fine now thanks.
