### ISSUE TITLE
Public data vs User data on APIs configuration

### ISSUE THREAD

**Issue by JackBurtonRulez** [claudiobernasconi/streamdeck-youtube#8]
Hi Claudio, the plugin works all but the channel subscribers for me (always = 0): I have the following question, should I choose the "User Data" in the following screen or is it enough to select Public Data?
![image](https://user-images.githubusercontent.com/27929828/88481197-53505000-cf5a-11ea-8060-b852bf60ae8a.png)

Thanks!

**Comment by claudiobernasconi** [comment]
Many people are using the plugin to show their channel subscribers, including me. If you try the channel Id of another channel, you could test if it a problem with your specific channel or a general problem. I am so sorry it does not work for you.

**Comment by JackBurtonRulez** [comment]
Hi Claudio,
sorry to bother you again but before giving up I'd like to make a final attempt... Here step by step (5 steps) what I do (and a pair of additional info). If all is correct for you, hey, it's something related to me or my channel so I'll take it and that's ok.

![Step1](https://user-images.githubusercontent.com/27929828/91756479-161c5500-ebcd-11ea-9bbf-29d896464db3.JPG)
![Step2](https://user-images.githubusercontent.com/27929828/91756484-187eaf00-ebcd-11ea-94dc-fb2cbed58c01.JPG)
![Step3](https://user-images.githubusercontent.com/27929828/91756493-1a487280-ebcd-11ea-95b8-4954069ec38c.JPG)
![Step4](https://user-images.githubusercontent.com/27929828/91756497-1c123600-ebcd-11ea-9aef-182ad08c20d6.JPG)
![Step5](https://user-images.githubusercontent.com/27929828/91756503-1d436300-ebcd-11ea-8097-a12a7fc0585c.JPG)
![Info1](https://user-images.githubusercontent.com/27929828/91756508-1f0d2680-ebcd-11ea-9332-11f44dfb634f.JPG)
![Info2](https://user-images.githubusercontent.com/27929828/91756510-203e5380-ebcd-11ea-8eb9-2d4791a6af84.JPG)

Thanks again a lot!
Fabrizio

**Comment by claudiobernasconi** [comment]
I cannot see anything wrong, to be honest. If you haven't already, check out the video, I created where I explain step-by-step how to set it up. Maybe we both don't see something right now. Give it a final try - perhaps it helps.

**Comment by JackBurtonRulez** [comment]
Hi Claudio, thanks for the continuous feedback! I wasn't able to find your video (just the tutorial on your channel on how to create a plugin using the toolkit): could you share the link? Meanwhile I'll be glad to share with you the Channel Id (you'll notice the view count is working while the subscriber's not, but I hope that all is working :) ).

**Comment by claudiobernasconi** [comment]
Sorry, I missed the link to the video. Here it is: https://www.youtube.com/watch?v=gqWgcuV5FK0

I checked your channel Id with my Stream deck (you sent it via DM). It turns out that I also have 0 subscribers for your channel. I tried to check your channel on Socialblade, and this is what I got:

![image](https://user-images.githubusercontent.com/6305202/91903009-d2941a80-eca2-11ea-89db-3e56d7ed3109.png)

It seems like something is set to private in your channel settings. If you can fix it so that Socialblade is able to access your data, I'm sure the Stream Deck plugin will also be able to access it.

Let me know if you're able to make any progress.

**Comment by JackBurtonRulez** [comment]
Hi Claudio,
first of all thanks again for all your effort supporting me, we solved the problem finally!

The issue was related to a Channel Setting, **"Display the number of people subscribed to my channel"** (see picture below): the misleading part of Youtube Mgmt (from my point of view) is that in the channel dashboard I can see the number of subscribers but that option set it public and so accessible from the APIs as far as I understand.
![Capture](https://user-images.githubusercontent.com/27929828/91903924-54387800-eca4-11ea-8542-93094c813d70.JPG)

**Comment by claudiobernasconi** [comment]
I'm very happy to hear that we were able to solve your issue. Also, I hope the documentation of this issue will help others fix the same problem.
