### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Kirin92** [claudiobernasconi/streamdeck-youtube#9]
I really need help.
I don't know how to get a working API Key.
First I tried it myself but now it's the E3 Error and I don't know what's wrong?

**Comment by claudiobernasconi** [comment]
Did you already watch my video where I explain step-by-step how to set it up? https://www.youtube.com/watch?v=gqWgcuV5FK0

**Comment by Kirin92** [comment]
OMG that helped a lot! Thank you! Didn't know there were a video tutorial.
